name: Deploy Backend

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Log in to Docker Hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - name: Build Docker image
        run: docker build -t nipunagarwal/summariser-backend .
      - name: Push Docker image
        run: docker push nipunagarwal/summariser-backend:latest

  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      - name: Pull Docker image from Docker Hub
        run: docker pull nipunagarwal/summariser-backend:latest
      - name: Stop and remove existing container
        run: |
          if [ $(docker ps -aq -f name=summariser-backend) ]; then
            docker stop summariser-backend
            docker rm summariser-backend
          fi
      - name: Run Docker container
        run: docker run -d -p 5000:5000 --name summariser-backend -e MONGODB_URL='${{ secrets.MONGODB_URL }}' -e JWT_SECRET='${{ secrets.JWT_SECRET }}' -e NODE_ENV='${{ secrets.NODE_ENV }}' -e HUGGINGFACE_API_KEY='${{ secrets.HUGGINGFACE_API_KEY }}' nipunagarwal/summariser-backend
